/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.seinfo.screen;

import br.com.seinfo.dal.Module_Connection;
import java.awt.Color;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author daniel
 */
public class Screen_Login extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public void log_user() {
        // Consult SQL name and password
        String sql = "SELECT * FROM tbusuarios WHERE login=? and senha=? ";
        
        // Execute SQL
        try {
            // PreparedStatement forExecute SQL
            pst = connection.prepareStatement(sql);
            pst.setString(1, lbl_user.getText());
            pst.setString(2, lbl_pswd.getText());
            rs = pst.executeQuery();
            
            
            if(rs.next()) {
                // Atribute content in column in DB 6(perfil)
                String perfil = rs.getString(6);
                //System.out.println(perfil);
                // Struct in perfil 
                if(perfil.equals("admin")) {
                    Screen_Main main_Screen = new Screen_Main();
                    main_Screen.setVisible(true);
                    //Enable Relatorio get Class
                    Screen_Main.menRel.setEnabled(true);
                    Screen_Main.menUser.setEnabled(true);
                    // Config txt nome referes column 2
                    Screen_Main.txt_user.setText(rs.getString(2));
                    
                    this.dispose();
                  // Disable full program  
                } else if(perfil.contains("user")) {
                    Screen_Main main = new Screen_Main();
                    main.setVisible(true);
                     // Config txt nome referes column 2
                    Screen_Main.txt_user.setText(rs.getString(2));
                    
                    this.dispose();
                }
                                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Usuário ou Senha incorreto", 
                    "Erro ao logar", JOptionPane.ERROR_MESSAGE);
        }
        
    }
 
    /**
     * Creates new form Screen_Login
     */
    public Screen_Login() {
              
        initComponents();
       // Call Module Connection 
       connection = Module_Connection.autentic();
        
       //System.out.println(connection);
       
       if(connection != null) {
           
       }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_acess = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_user = new javax.swing.JTextField();
        lbl_pswd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(170, 12, 12));
        setUndecorated(true);

        btn_acess.setText("Acessar");
        btn_acess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acessActionPerformed(evt);
            }
        });

        btn_exit.setText("Sair");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 3, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 215));
        jLabel3.setText("OS INFORMÁTICA");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seinfo/icons/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cantarell", 2, 17)); // NOI18N
        jLabel1.setText("Usuário");

        jLabel2.setFont(new java.awt.Font("Cantarell", 2, 17)); // NOI18N
        jLabel2.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_acess, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_user)
                    .addComponent(lbl_pswd))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_acess)
                    .addComponent(btn_exit))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        
        int yes = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?", "Sair do sistema", JOptionPane.YES_NO_OPTION);
        if(yes == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Sempre salve as ordens de serviço", "Lembrete", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_acessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acessActionPerformed
        log_user();
    }//GEN-LAST:event_btn_acessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  
              new Screen_Login().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acess;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField lbl_pswd;
    private javax.swing.JTextField lbl_user;
    // End of variables declaration//GEN-END:variables
}
