/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.seinfo.screen;

import br.com.seinfo.dal.Module_Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author daniel
 */
public class Screen_Main extends javax.swing.JFrame {

    Connection connection;
    /**
     * Creates new form Screen_Main
     */
    public Screen_Main() {
        initComponents();
        //Autentic Bd
        connection = Module_Connection.autentic();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCli = new javax.swing.JMenuItem();
        menOS = new javax.swing.JMenuItem();
        menUser = new javax.swing.JMenuItem();
        menExit = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menServ = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menDoc = new javax.swing.JMenuItem();
        menAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 243, 243));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 2, 24)); // NOI18N
        jLabel1.setText("Técnico Habilitado");

        txt_user.setFont(new java.awt.Font("Cantarell", 2, 19)); // NOI18N
        txt_user.setText("Nome Completo do User");

        txt_date.setFont(new java.awt.Font("Cantarell", 2, 19)); // NOI18N
        txt_date.setText("Data");

        desktop.setBackground(new java.awt.Color(35, 36, 57));
        desktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/seinfo/icons/empresa.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cantarell", 2, 24)); // NOI18N
        jLabel2.setText("Data/Hora");

        jMenuBar1.setBackground(new java.awt.Color(31, 32, 32));
        jMenuBar1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        menCad.setText("Cadastros");
        menCad.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        menCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menCli.setText("Cliente");
        menCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCliActionPerformed(evt);
            }
        });
        menCad.add(menCli);

        menOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menOS.setText("Ordem de Serviço");
        menOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOSActionPerformed(evt);
            }
        });
        menCad.add(menOS);

        menUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menUser.setText("Usuários");
        menUser.setEnabled(false);
        menUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menUserActionPerformed(evt);
            }
        });
        menCad.add(menUser);

        menExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menExit.setText("Sair");
        menExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menExitActionPerformed(evt);
            }
        });
        menCad.add(menExit);

        jMenuBar1.add(menCad);

        menRel.setText("Relatórios");
        menRel.setEnabled(false);
        menRel.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menRel.add(jMenuItem1);

        menServ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menServ.setText("Serviços");
        menServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menServActionPerformed(evt);
            }
        });
        menRel.add(menServ);

        jMenuBar1.add(menRel);

        jMenu3.setText("Ajuda");
        jMenu3.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N

        menDoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.ALT_MASK));
        menDoc.setText("Documentação");
        jMenu3.add(menDoc);

        menAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menAbout.setText("Sobre");
        menAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(750, 750, 750)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txt_date)
                            .addComponent(txt_user)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txt_user)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_date)
                .addGap(40, 40, 40)
                .addComponent(jLabel3))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCliActionPerformed
        Screen_Client cli = new Screen_Client();
        cli.setVisible(true);
        desktop.add(cli);
    }//GEN-LAST:event_menCliActionPerformed

    private void menAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menAboutActionPerformed
        // Call screen About
        Screen_About about = new Screen_About();
        about.setVisible(true);
        
    }//GEN-LAST:event_menAboutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/YYYY");
        String data = sdf.format(new Date());
        txt_date.setText(data);
              
    }//GEN-LAST:event_formWindowActivated

    private void menExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menExitActionPerformed
        // Show JOptionPane
        int sair = JOptionPane.showConfirmDialog(null, "Deseja sair realmente?","Sair do sistema", JOptionPane.YES_NO_OPTION);
        
        if(sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(null, "Sempre salve as ordens de serviço!","Lembrete", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_menExitActionPerformed

    private void menUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menUserActionPerformed
        // Call Screen_User
        Screen_User user = new Screen_User();
        user.setVisible(true);
        desktop.add(user);
        
    }//GEN-LAST:event_menUserActionPerformed

    private void menOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOSActionPerformed
        Screen_OS os = new Screen_OS();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_menOSActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Generated form client
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão "
                + "desse relatório na tela?","Atenção", JOptionPane.YES_NO_OPTION);
        
        if (confirma == JOptionPane.YES_OPTION) {
            // Print form clients
            try {
                // Class JasPerPrint prepared print
                JasperPrint print = JasperFillManager.fillReport(
                        "/home/daniel/Documents/project_osinfoX/reports/clientes.jasper",
                        null,connection);
                
                // View form after print
                JasperViewer.viewReport(print, false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menServActionPerformed
        
           //Generated form client
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a emissão "
                + "desse relatório na tela?","Atenção", JOptionPane.YES_NO_OPTION);
        
        if (confirma == JOptionPane.YES_OPTION) {
            // Print form clients
            try {
                // Class JasPerPrint prepared print
                JasperPrint print = JasperFillManager.fillReport(
                        "/home/daniel/Documents/project_osinfoX/reports/servicos.jasper",
                        null,connection);
                
                // View form after print
                JasperViewer.viewReport(print, false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_menServActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menAbout;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCli;
    private javax.swing.JMenuItem menDoc;
    private javax.swing.JMenuItem menExit;
    private javax.swing.JMenuItem menOS;
    public static javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menServ;
    public static javax.swing.JMenuItem menUser;
    private javax.swing.JLabel txt_date;
    public static javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
